# This is a basic workflow to help you get started with Actions

name: Notify Tester

# Controls when the workflow will run
on:
  push:
    branches:
      - v1
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under , so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          curl -H "Content-Type: application/json" -d '
          {
            "text": "Build is complete for ${{ github.event.repository.name }}"             
          }' ${{ secrets.WEBHOOK_URL }}
      
      - name: Tag the user who triggered the workflow
        run: |
          echo "The user who triggered this workflow is: ${{ env.GITHUB_ACTOR }} under the repo ${{ env.GITHUB_WORKSPACE }} "
