name: Get User who started workflow

on:
  push:
    branches:
      - v1

env:
  USERNAME: ${{ env.GITHUB_ACTOR }}

steps:
  - name: Print User who started workflow
    run: |
      echo "The user who started this workflow is: ${USERNAME}"
