name: Get User who started workflow

on:
 workflow_call:
  inputs:
    JOB_CONFIG_JSON:
      type: string
      required: true



env:
  JOB_CONFIG_JSON: ${{ inputs.JOB_CONFIG_JSON }}
  
  
jobs:
 run_code:
  runs-on: ubuntu-latest
  steps:
      - name: Output
        run: |
          echo ${{ env.JOB_CONFIG_JSON }}
