name: Get User who started workflow
run-name: master workflow

on:
 workflow_call:
  inputs:
    JOB_CONFIG_JSON:
      type: string
      required: true



env:
  JOB_CONFIG_JSON: ${{ inputs.JOB_CONFIG_JSON }}
jobs:
  
 run_code:
  runs-on: ubuntu-latest
  steps:
      - uses: actions/checkout@v2
      - name: Output
        run: |
          echo "The name is: ${{ env.JOB_CONFIG_JSON }}"
