name: Notify_Demo
run-name: v2 workflow

on:
  push:
    branches:
      - v2
  workflow_call:
  workflow_dispatch:

jobs:
  
 stage_1:
  runs-on: ubuntu-latest
  steps:
      - name: Workflow
        run: |
          echo "${{github.actor}} triggered ${{github.workflow}} for ${{ github.event.repository.name }} on  branch ${{ github.GITHUB_REF_NAME }}"
 notify_teams_failure:
  runs-on: ubuntu-latest
  needs: stage_1
  if: failure()
  steps:
      - name: Workflow
        run: |
          echo "The build failed for ${{github.workflow}} "



